/* ============================================================
 * Spec Data — Samsung
 * isRumor: true → 미출시/루머 플래그
 * ============================================================ */
window.SPEC_DATA = window.SPEC_DATA || {};
window.SPEC_DATA['samsung'] = {
  brand: 'Samsung',
  models: [
    {
      key: 's26',
      model: 'Galaxy S26',
      launch: '2026.03.11',
      isRumor: false,
      market: '글로벌',
      segment: 'Premium Volume',
      display: {
        size: '6.3"',
        panelSupplier: 'SDC',
        panelType: 'M16 LTPO',
        resolution: '2340×1080 (FHD+)',
        ppi: '~410',
        hzRange: '1–120Hz',
        brightness: '2600nit',
        pwm: '480Hz',
        hdr: 'HDR10+',
        notes: ''
      },
      soc: 'SD 8 Elite Gen5 / Exynos 2600',
      ram: '12GB',
      storage: '256GB / 512GB',
      battery: '4300mAh',
      charging: { wired: '25W', wireless: '15W' },
      camera: { main: '50MP f/1.4', tele: '10MP 3x f/2.4', uw: '12MP f/2.2' },
      weight: '162g',
      waterproof: 'IP68',
      os: 'Android 15 / One UI 7',
      notes: '7년 OS 지원 · 컴팩트 플래그십'
    },
    {
      key: 's26plus',
      model: 'Galaxy S26+',
      launch: '2026.03.11',
      isRumor: false,
      market: '글로벌',
      segment: 'Premium Volume',
      display: {
        size: '6.7"',
        panelSupplier: 'SDC',
        panelType: 'M16 LTPO',
        resolution: '3120×1440 (QHD+)',
        ppi: '~513',
        hzRange: '1–120Hz',
        brightness: '2600nit',
        pwm: '480Hz',
        hdr: 'HDR10+',
        notes: ''
      },
      soc: 'SD 8 Elite Gen5 / Exynos 2600',
      ram: '12GB',
      storage: '256GB / 512GB',
      battery: '4900mAh',
      charging: { wired: '45W', wireless: '20W' },
      camera: { main: '50MP f/1.8', tele: '10MP 3x f/2.4', uw: '12MP f/2.2' },
      weight: '190g',
      waterproof: 'IP68',
      os: 'Android 15 / One UI 7',
      notes: '7년 OS 지원 · QHD+ 대형'
    },
    {
      key: 's26u',
      model: 'Galaxy S26 Ultra',
      launch: '2026.03.11',
      isRumor: false,
      market: '글로벌 + 중국',
      segment: 'Imaging Flagship',
      display: {
        size: '6.9"',
        panelSupplier: 'SDC',
        panelType: 'M16 LTPO',
        resolution: '3120×1440 (QHD+)',
        ppi: '~500',
        hzRange: '1–120Hz',
        brightness: '2600nit',
        pwm: '480Hz',
        hdr: 'HDR10+',
        notes: 'Privacy Display (하드웨어 측각차단) · 세계 최초'
      },
      soc: 'SD 8 Elite Gen5 (custom)',
      ram: '16GB',
      storage: '256GB / 512GB / 1TB',
      battery: '5000mAh',
      charging: { wired: '60W', wireless: '25W' },
      camera: {
        main: '200MP f/1.4',
        tele: '10MP 3x + 50MP 5x f/2.9',
        uw: '50MP'
      },
      weight: '약 218g',
      waterproof: 'IP68',
      os: 'Android 15 / One UI 7',
      notes: 'S Pen 지원 · 7년 OS · Privacy Display'
    },
    {
      key: 'zfold7',
      model: 'Galaxy Z Fold 7',
      launch: '2026 Q3 예상',
      isRumor: true,
      market: '글로벌',
      segment: 'Foldable',
      display: {
        size: '내부 ~7.7" / 커버 ~6.3"',
        panelSupplier: 'SDC',
        panelType: 'M16 LTPO (예상)',
        resolution: '내부 QHD+ / 커버 HD+',
        ppi: '—',
        hzRange: '1–120Hz',
        brightness: '~2600nit (예상)',
        pwm: '—',
        hdr: 'HDR10+',
        notes: '얇아진 힌지 · 방수 강화 예상'
      },
      soc: 'SD 8 Elite Gen5 또는 Gen6 (예상)',
      ram: '12GB (예상)',
      storage: '256GB / 512GB',
      battery: '~4400mAh (예상)',
      charging: { wired: '25W (예상)', wireless: '15W (예상)' },
      camera: { main: '50MP', tele: '10MP 3x', uw: '12MP' },
      weight: '—',
      waterproof: 'IPX8 (예상)',
      os: 'Android 16 / One UI 8 (예상)',
      notes: '루머 기반 · 미확인 스펙 다수'
    },
    {
      key: 'zflip7',
      model: 'Galaxy Z Flip 7',
      launch: '2026 Q3 예상',
      isRumor: true,
      market: '글로벌',
      segment: 'Compact Foldable',
      display: {
        size: '메인 ~6.9" / 커버 ~4.1"',
        panelSupplier: 'SDC',
        panelType: 'LTPO (예상)',
        resolution: '메인 FHD+ / 커버 720p',
        ppi: '—',
        hzRange: '1–120Hz',
        brightness: '—',
        pwm: '—',
        hdr: 'HDR10+',
        notes: '커버 디스플레이 확대 예상'
      },
      soc: 'Exynos 2600 또는 SD 8 Elite Gen5 (예상)',
      ram: '12GB (예상)',
      storage: '256GB / 512GB',
      battery: '~4000mAh (예상)',
      charging: { wired: '25W', wireless: '15W' },
      camera: { main: '50MP', tele: '—', uw: '12MP' },
      weight: '—',
      waterproof: 'IPX8 (예상)',
      os: 'Android 16 / One UI 8 (예상)',
      notes: '루머 기반 · 미확인 스펙 다수'
    },
    {
      key: 's27u',
      model: 'Galaxy S27 Ultra',
      launch: '2027 Q1 예상',
      isRumor: true,
      market: '글로벌',
      segment: 'Imaging Flagship',
      display: {
        size: '~6.9"',
        panelSupplier: 'SDC',
        panelType: 'M17 또는 M16 LTPO (예상)',
        resolution: 'QHD+ 이상 (예상)',
        ppi: '—',
        hzRange: '1–120Hz',
        brightness: '2600nit+ (예상)',
        pwm: '—',
        hdr: 'HDR10+',
        notes: 'Pro 라인 부활 검토 중'
      },
      soc: 'SD 8 Elite Gen6 또는 Exynos 2700 (예상)',
      ram: '16GB (예상)',
      storage: '256GB ~ 1TB',
      battery: '5000mAh (예상)',
      charging: { wired: '65W+ (예상)', wireless: '25W' },
      camera: { main: '200MP+', tele: '10x+ (예상)', uw: '50MP' },
      weight: '—',
      waterproof: 'IP68 (예상)',
      os: 'Android 17 / One UI 9 (예상)',
      notes: '루머 기반 · S27 Pro 라인 재도입 가능성'
    }
  ]
};
